### ISSUE TITLE
Problem with PHP8

### ISSUE THREAD

**Issue by Juergen-aus-Zuendorf** [giterlizzi/dokuwiki-plugin-advanced#15]
Hi,

after updating the dokuwiki server to PHP8 the advanced plugin fails with the following error message when I go to the konfig page of the admin console:

```
dokuwiki\Exception\FatalException: Array and string offset access syntax with curly braces is no longer supported
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the advanced plugin.
```
What can I do?

Best regards
Juergen

**Comment by fiwswe** [comment]
The fix is very easy:

In Line 489 of the file `…/lib/plugins/advanced/ZipLib.class.php` replace:
`$last = $val{strlen($val)-1};`
with
`$last = substr($val, -1);`


The PR https://github.com/giterlizzi/dokuwiki-plugin-advanced/pull/16 will also work I think. But for my taste the syntax is too complicated. Using `substr()` is much more straight forward and possibly more efficient IMHO.

HTH
fiwswe

**Comment by tool-buddy** [comment]
Following the fix from https://github.com/giterlizzi/dokuwiki-plugin-advanced/commit/0476d0e4c44cbbfc837aa63e8207422d46f7c884, shouldn't the file [ZipLib.class.php](https://github.com/giterlizzi/dokuwiki-plugin-advanced/blob/master/ZipLib.class.php) be removed?

**Comment by fiwswe** [comment]
I agree, the file does not seem to be used anymore in the latest published version of the plugin.

The only previous use was in the admin/export.php file AFAICT and exporting works fine without the file in my test wiki.

fiwswe

**Comment by fiwswe** [comment]
I have created PR #20 to remove the file.

fiwswe
